---
  - name: Simple LAMP application in Ubuntu
    hosts: target1
    become: true
    tasks:
      - name: Upgrade all apt packages
        become: true
        become_user: root
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Install firewalld
        apt:
          name: firewalld
          state: present
      
      - name: Start firewalld 
        service:
          name: firewalld
          state: started

      - name: Enable firewalld
        systemd:
          name: firewalld
          enabled: yes
      
      - name: Install mariadb server
        apt:
          name: mariadb-server
          state: present

      - name: Start DB server
        service:
          name: mariadb
          state: started
      
      - name: Enable DB server
        systemd:
          name: mariadb
          enabled: yes
       
      - name: Configuring firewall for Database
        firewalld:
          port: 3306/tcp
          zone: public
          permanent: yes
          immediate: yes
          state: enabled
    
      - name: install python-pip
        apt: 
          name: python3-pip
          state: present

      - name: Make sure pymysql is present
        pip:
          name: pymysql
          state: present

      - name: Install mysql
        pip:
          name: mysql-connector
          state: latest

      - name: Create a new database with name "ecomdb"
        mysql_db:
          login_unix_socket: /var/run/mysqld/mysqld.sock
          name: ecomdb
          state: present

      - name: Create new user "ecomuser"
        mysql_user:
          login_unix_socket: /var/run/mysqld/mysqld.sock
          host: localhost
          name: ecomuser
          password: ecompassword
          priv: '*.*:ALL,GRANT'
          state: present   

      - name: cloning a git repo
        git: 
          repo: 'https://github.com/Vasanthkabilan/learning-app-ecommerce.git'
          dest: /opt
          update: yes
        
      - name: import ecom-table sql file
        mysql_db:
          login_unix_socket: /var/run/mysqld/mysqld.sock
          state: import
          name: ecomdb
          target: /opt/db-load-script.sql
        ignore_errors: True

      - name: Deploy and Configure web
        apt:
          name:
            - apache2
            - php
            - php-mysql
          state: present

      - name: Configuring firewall for apache2
        firewalld:
          port: 80/tcp
          zone: public
          permanent: yes
          immediate: yes
          state: enabled

      - name: Start httpd web server
        service: 
          name: apache2
          state: started
      
      - name: Enable httpd
        systemd:
          name: apache2
          enabled: yes

      - name: Changing index.directory
        template:
          src: /home/ubuntu/test-project/dir.conf.j2
          dest: /etc/apache2/mods-enabled/dir.conf
        notify:
          - Reload Apache
      
      - name: Delete index html file
        file:
          path: /var/www/html/index.html
          state: absent
        ignore_errors: True

      - name: copy index file 
        command: "cp /opt/index.php  /var/www/html"

      - name: Changing host in index.php
        template:
          src: /home/ubuntu/test-project/index.php.j2
          dest: /var/www/html/index.php
    
    handlers:
      - name: Reload Apache
        service:
          name: apache2
          state: reloaded

      - name: Restart Apache
        service:
          name: apache2
          state: restarted

