---
# handlers file for config_web
- name: Reload Apache
        service:
          name: apache2
          state: reloaded

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Start apache
  service: 
    name: apache2
    state: started

- name: Enable apache
  systemd:
    name: apache2
    enabled: yes
